auth:
    sfdc:
        clientid: "3MVG9CG8tifMyyO33Ys0ROWOZNzG.4C9jF7UWFZ9Kb91DOZs2A4VWMyTldMfIMlwssmNYRQH4erEHR6jdd7a5"
        keystore:
            path: "certificates/certsa.jks"
        principal:
            user: "maha@megabytes-tech.com.fleetdev"
        tokenurl: "https://test.salesforce.com/services/oauth2/token"
sftp:
    archive:
        path: "/QA/Archive/FleetPrices/"
    error:
        path: "/QA/Error/FleetPrices/"
    file:
        base: "base.txt"
        price: "items.txt"
        read:
            path:
                base: "/Users/shaliniamith/Downloads/FILES/base.txt"
                price: "/Users/shaliniamith/Downloads/FILES/items.txt"
    host: "0.0.0.0"
    username: "s"
    working:
        path: "/Users/shaliniamith/Downloads/FILES"
static:
     family: 'CarBaseModel'
     productClassification : 'Configurator'
     masterDataSource: 'STANDARD' 