auth:
    sfdc:
        clientid: "3MVG9CG8tifMyyO33Ys0ROWOZNzG.4C9jF7UWFZ9Kb91DOZs2A4VWMyTldMfIMlwssmNYRQH4erEHR6jdd7a5"
        keystore:
            path: "certificates/certsa.jks"
        principal:
            user: "maha@megabytes-tech.com.fleetdev"
        tokenurl: "https://test.salesforce.com/services/oauth2/token"
sftp:
    archive:
        path: "/DEV/Archive/FleetPrices/"
    error:
        path: "/DEV/Error/FleetPrices/"
    file:
        base: "carbase.txt"
        price: "item.txt"
        read:
            path:
                base: "/DEV/FleetPrices/carbase.txt"
                price: "/DEV/FleetPrices/item.txt"
    host: "152.107.143.42"
    username: "Mulesoft"
    working:
        path: "/DEV/FleetPrices/"

static:
     family: 'CarBaseModel'
     productClassification : 'Configurator'
     masterDataSource: 'STANDARD' 