auth:
    sfdc:
        clientid: "3MVG9CG8tifMyyO370xVuNbqB.VqMH1EF7Lk9bLsGYsXEaE3e2RfTLWYGIhZjgfDnFwH6j6Ja0bma94Wr0nnO"
        keystore:
            path: "certificates/sit.jks"
        principal:
            user: "muleapi@vwsa.com"
        tokenurl: "https://test.salesforce.com/services/oauth2/token"
sftp:
    archive:
        path: "/DEV/Archive/FleetPrices/"
    error:
        path: "/DEV/Error/FleetPrices/"
    file:
        base: "base.txt"
        price: "items.txt"
        read:
            path:
                base: "/DEV/FleetPrices/base.txt"
                price: "/DEV/FleetPrices/items.txt"
    host: "152.107.143.30"
    username: "Mulesoft"
    working:
        path: "/DEV/FleetPrices/"

static:
     family: 'CarBaseModel'
     productClassification : 'Configurator'
     masterDataSource: 'STANDARD' 